### ISSUE TITLE
The project is broken

### ISSUE THREAD

**Issue by FleksisLV** [insthync/bomber-io-demo#1]
For some reason there is lot of errors, couldn't fix ,is there any setup guide the assetstore docomentation is not for this  ?

**Comment by FleksisLV** [comment]
Bought asset store VERSION WORKING :d

**Comment by insthync** [comment]
What are those error?

**Comment by FleksisLV** [comment]
\LiteNetLibManager\Plugins\ZLogger\IAsyncLogProcessor.cs(7,43): error CS0433: The type 'IAsyncDisposable' exists in both 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

**Comment by FleksisLV** [comment]
\LiteNetLibManager\Plugins\ZLogger\AsyncStreamLineMessageWriter.cs(12,69): error CS0433: The type 'IAsyncDisposable' exists in both 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

**Comment by FleksisLV** [comment]
Battle IO I bought it today, but still get these two errors on both 2021 and 2022 unity.

**Comment by FleksisLV** [comment]
I got fixed the errors by using unity 2020 but the server won't work on window the server get's froze with all bot's , you can join walk around  but can't hit.

**Comment by insthync** [comment]
Try to pull the latest version of LiteNetLibManager if you want to fix those errors with 2021/2022, as I try it is working as intend.

**Comment by FleksisLV** [comment]
Yes but why the bot's don't show up and they won't move either when in dedicated server ? I'am using the one from assetstore.

**Comment by insthync** [comment]
Why mine is working ? 

https://youtu.be/lzubliGfg6E

I think I will remove it from the asset store page soon, I intend to keep it for updating (by buying another with a discounted price), I also wrote on the page that it is open-source but you guys still buying it.

**Comment by insthync** [comment]
If you follow dedicate server document, and it is not working, then, try to attach the server log files

**Comment by FleksisLV** [comment]
I fixed the issue with 2022 , by updating to never version of  LiteNetLibManager but there still has the bug where the bot's won't move and also  the lan server won't work anymore on 2022, where i can enable the loging for server since i'am new to this kit i don't know mostly nothing, also i noticed there is no server list or anything and photon has that's mean it's better to use the photon version but it's will be off soon since it's old  ?Also for LitNetLib I have to make for each server button that's correct ?, Is there any chance you can send me the files what you got as assetpack, since the one's when put together on github doesn't work it's corrupted or something, and for the assetstore version there is something wrong when start the server on windows. I didn't try do on linux maybe that's the issue. Thanks.
The image from asset store battle IO Dedicated server all the bots froze
![image_2024-01-03_170941266](https://github.com/suriyun-io-games/demo-bomber-io/assets/45308506/ac46ca5b-08bd-4492-8f56-48e2a42f83e0)

**Comment by FleksisLV** [comment]
I just want make the server for testing on windows so i don't have to buy or setup linux for development.

**Comment by FleksisLV** [comment]
I don't know how your work, i did as the tutorial on https://suriyun-production.github.io/battle-io-docs/#/pages/017-_BATTLE-IO--BOMBER-IO--SHOOTER-IO---Dedication-Command-Line-Arguments . also i bought it since the one on github not work for some reason when setup on my system,. Everything else beside now the updated LiteNetLibManager  is the original from latest version from asset store and i got this strange server freeze for the bots.
they sometimes fight if enough close.

**Comment by FleksisLV** [comment]
Hi can you help me out please, you haven't answered for 2 days and i still haven't figured out my self, please, i will pay you more if needed true donation just tell me how much... Please it's important i want to make some cool game out of this base but, i have no idea why i got so much bug's, i want this as base because i know you do professional work as i have worked a lot with your mmorpg.

**Comment by insthync** [comment]
Did you try to join a game, not sure that the case bot froze is what I intend to do to improve performance while there is no players in the room or something.
